#!/bin/bash
FILE=cliente
make $FILE
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=full --log-file="../logs/valgrind_cliente.log" --show-possibly-lost=no --show-reachable=no --num-callers=20 ./$FILE
fi