#!/bin/bash
FILE=comanda
make $FILE
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=yes --log-file="../logs/valgrind_comanda.log" --show-possibly-lost=no --show-reachable=no --num-callers=20 ./$FILE
fi